image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.11

environment:
  GITHUB_TOKEN:
    secure: Ti46nPnZgFh0nRteU6ma0EhJnCTW7PaMn9hnnewZl4gBFPyRQnXNCwGog02+MRLX

install:
- pip install -r requirements.txt

build_script:
- flet pack main.py --name csv-to-xlsx-conversor --icon icon.png --product-name csv-to-xlsx-conversor --product-version "1.2.3" --copyright "Copyright (c) 2022 YourCompany Inc."

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a csv-to-xlsx-conversor-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: csv-to-xlsx-conversor-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf csv-to-xlsx-conversor-macos.tar.gz -C dist csv-to-xlsx-conversor.app

  artifacts:
  - path: csv-to-xlsx-conversor-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf csv-to-xlsx-conversor-linux.tar.gz -C dist csv-to-xlsx-conversor

  artifacts:
  - path: csv-to-xlsx-conversor-linux.tar.gz

