[configuration.file]
encoding_file = "utf-8"
delimiter_file = ";"

[filters.exclude]
rows_contains_partial = [ "Tomabmento",]
rows_contains_terms = [ "Unidade: 1287 - CAMPUS UNIVERSITARIO DE ALTAMIRA (11.10)",]
rows_excepty_first = [ "",]
rows_empety = true
columns_number = [ "12", "13", "14",]
